RunConsoleCommand("gmod_mcore_test", "1")
RunConsoleCommand("mat_queue_mode", "-1")
RunConsoleCommand("cl_threaded_bone_setup", "1")
RunConsoleCommand("r_queued_ropes", "1")
RunConsoleCommand("cl_detaildist", "0")
RunConsoleCommand("cl_detailfade", "0")
RunConsoleCommand("r_shadows", "0")
RunConsoleCommand("r_shadowrendertotexture", "0")
